// DICAS DOS BOTÕES (Lote 1, item 14) — fonte única do "o que este botão faz": nome da ferramenta, uma
// frase curta e simples e o atalho de teclado. A janelinha (components/mae/Dicas.tsx) acha a dica pelo
// atributo data-* do botão (ex.: data-desfazer → "desfazer"; data-modo-editor="tema" → "modo-editor=tema")
// e, se não achar, pelo texto do botão. Sem dica no dicionário, usa o title do botão ("Nome — frase (Atalho)").

export interface Dica { nome: string; frase: string; atalho?: string }

const d = (nome: string, frase: string, atalho?: string): Dica => ({ nome, frase, ...(atalho ? { atalho } : {}) })

/** Por atributo data-* do botão (sem o "data-"); "atributo=valor" para botões com o mesmo atributo. */
export const DICAS: Record<string, Dica> = {
  // ── barra do editor ──
  'modo-editor=base': d('1. Base', 'Monta os moldes, as faces e as partes do kit — uma vez só.'),
  'modo-editor=tema': d('2. Tema', 'Veste a base com papéis, elementos e o nome; vale para todas as caixas.'),
  'modo-editor=imagem': d('3. Editor livre', 'Uma arte solta, sem molde (convite, tag, topo de bolo…), com camadas, texto e máscaras.'),
  // ── Lote 2: barra de ícones da esquerda (uma função por ícone; clicar de novo fecha) ──
  'funcao=passo-1': d('Moldes', 'Importe os moldes e posicione na prancheta (alinhar, centralizar, setas).'),
  'funcao=passo-2': d('Pranchetas', 'As folhas da área de trabalho: tamanho, orientação e posição.'),
  'funcao=passo-3': d('Faces', 'As faces de cada molde (laço, dividir, unir, furos).'),
  'funcao=passo-4': d('Partes', 'Agrupe as faces iguais (FRENTE, LATERAL…) para a arte valer em todas.'),
  'funcao=passo-5': d('Enquadramento', 'Como a arte da parte cabe em cada face.'),
  'funcao=passo-6': d('Nome e textos', 'Onde ficam NOME, IDADE, HASHTAG e @ em cada molde.'),
  'funcao=passo-7': d('Identidade', 'Logo, QR e @ do ateliê nos moldes.'),
  'funcao=passo-8': d('Arte inteligente', 'Sobra da impressão e o papel das abas.'),
  'funcao=passo-9': d('Salvar', 'Dê nome e salve a base na Biblioteca.'),
  'funcao=marcas': d('Marca de registro', 'A marca da máquina de corte em cada prancheta (✓ encaixa, ⚠️ confira).'),
  'funcao=papeis': d('Papéis', 'Os papéis de fundo — arraste para uma parte ou face.'),
  'funcao=elementos': d('Elementos', 'Os elementos com fundo transparente.'),
  'funcao=cor': d('Cor', 'Preencha a parte com uma cor lisa.'),
  'funcao=partes': d('Partes e camadas', 'As partes do kit e as camadas de cada uma.'),
  'funcao=texto': d('Texto', 'Fonte, tamanho, estilos e efeitos do nome, idade e hashtag.'),
  'funcao=moldurinha': d('Moldurinha', 'Bordinha interna na face (contínua ou pesponto).'),
  'funcao=transicao': d('Transição', 'O 2º papel aparece por cima e some suavemente.'),
  'funcao=apliques': d('Apliques 3D', 'Folhas de impressos e silhuetas dos apliques.'),
  'funcao=exportar': d('Exportar', 'Arte pra aprovação e arquivo pra impressão.'),
  'funcao=pronto': d('Tema pronto', 'Já tem a arte pronta (PDF/PNG)? Cadastre e ponha nome, idade e hashtag em massa.'),
  'funcao=loja': d('Loja da Naty', 'Packs de temas prontos.'),
  // ── Lote 2: tema pronto ──
  'fechar-guia-pronto': d('Entendi', 'Fecha o passo a passo (ele não aparece de novo).'),
  'subir-pronto': d('Escolher arquivo', 'Um PDF (uma caixa por página) ou PNG do computador — uma cópia fica em Temas/.'),
  'atualizar-prontos': d('Atualizar', 'Lê de novo a pasta Temas/ (se você copiou arquivos para lá).'),
  'arquivo-tema': d('Usar este arquivo', 'Cadastra este arquivo como tema pronto.'),
  'criar-pronto': d('Criar tema pronto', 'Cada página vira uma prancheta; NOME, IDADE e HASHTAG entram na 1ª página.'),
  'pronto-posicao': d('Posição dos textos', 'Arraste as caixas de NOME, IDADE e HASHTAG na folha.'),
  'pronto-estilo': d('Estilo do texto', 'Fonte, cor, contorno e sombra do nome, idade e hashtag.'),
  'salvar-pronto': d('Salvar', 'Grava o tema pronto na Biblioteca (e na nuvem).'),
  'novo-pronto': d('Cadastrar outro', 'Fecha este tema e começa outro tema pronto.'),
  // ── Lote 2: posição dos moldes (item 15) ──
  'centralizar-moldes': d('Centralizar', 'Põe os moldes selecionados no centro da área útil da prancheta.'),
  'alinhar=esquerda': d('Alinhar à esquerda', 'Encosta na esquerda da prancheta (ou do primeiro selecionado).'),
  'alinhar=centro': d('Centralizar na horizontal', 'Centro horizontal da prancheta (ou dos selecionados).'),
  'alinhar=direita': d('Alinhar à direita', 'Encosta na direita da prancheta (ou dos selecionados).'),
  'alinhar=topo': d('Alinhar em cima', 'Encosta no topo da prancheta (ou dos selecionados).'),
  'alinhar=meio': d('Centralizar na vertical', 'Meio vertical da prancheta (ou dos selecionados).'),
  'alinhar=base': d('Alinhar embaixo', 'Encosta na base da prancheta (ou dos selecionados).'),
  'distribuir=h': d('Distribuir na horizontal', 'Espaço igual entre os moldes (3 ou mais), da esquerda para a direita.'),
  'distribuir=v': d('Distribuir na vertical', 'Espaço igual entre os moldes (3 ou mais), de cima para baixo.'),
  'alinhar-a=prancheta': d('Alinhar à prancheta', 'Move os selecionados juntos até a borda/centro da área útil (fora da marca).'),
  'alinhar-a=selecao': d('Alinhar entre si', 'Alinha cada molde selecionado aos outros.'),
  // ── Lote 2: exportação e edição em massa ──
  'abrir-arquivo': d('Abrir o arquivo', 'Abre o arquivo gerado numa aba nova.'),
  'abrir-pasta': d('Mostrar a pasta', 'Abre a pasta da exportação no seletor do computador.'),
  'copiar-caminho': d('Copiar caminho', 'Copia o caminho da pasta para colar no Explorer.'),
  'marca-todas-a4': d('Usar em todas as A4', 'Usa esta marca em todas as pranchetas A4.'),
  'miniatura': d('Prévia', 'Clique para ver a arte ampliada.'),
  'zoom-menos': d('Diminuir', 'Afasta a vista (zoom menor).', 'Ctrl −'),
  'zoom-mais': d('Aumentar', 'Aproxima a vista (zoom maior).', 'Ctrl +'),
  'olho-tema': d('Mostrar / ocultar', 'Esconde a camada sem apagar.'),
  'subir-camada-tema': d('Subir camada', 'Passa a camada para cima das outras.'),
  'descer-camada-tema': d('Descer camada', 'Passa a camada para baixo das outras.'),
  'aplicar-preset': d('Aplicar estilo', 'Aplica este conjunto de efeitos no texto ou na camada.'),
  'excluir-slot': d('Excluir posição', 'Apaga esta posição de texto.'),
  orientacao: d('Orientação', 'Retrato (em pé) ou paisagem (deitada) para a próxima prancheta.'),
  'alinhar-texto=left': d('Alinhar à esquerda', 'O texto encosta na esquerda da caixa.'),
  'alinhar-texto=center': d('Centralizar', 'O texto fica no meio da caixa.'),
  'alinhar-texto=right': d('Alinhar à direita', 'O texto encosta na direita da caixa.'),
  'fechar-tema': d('Fechar o tema', 'Fecha o tema aberto (salve antes).'),
  folha: d('Tamanho da folha', 'A4, A5, A6 ou personalizado — vale para a próxima prancheta criada.'),
  'nova-prancheta': d('Nova área de trabalho', 'Começa de novo com uma prancheta vazia (Ctrl+Z traz a anterior de volta).'),
  'adicionar-prancheta': d('Nova prancheta', 'Acrescenta mais uma folha nesta área de trabalho, no tamanho e orientação escolhidos.'),
  organizar: d('Organizar', 'Arruma as pranchetas em linha, em coluna ou em grade.'),
  desfazer: d('Desfazer', 'Volta o último passo.', 'Ctrl+Z'),
  refazer: d('Refazer', 'Refaz o passo desfeito.', 'Ctrl+Shift+Z'),
  'tamanho-real': d('Tamanho real', '100 mm na tela = 100 mm de verdade (calibre a tela antes).', 'Ctrl+1'),
  'abrir-massa': d('Pedidos (massa)', 'Gera a arte de vários pedidos de uma vez.'),
  'abrir-tutorial': d('Como usar', 'Abre o passo a passo do Método MAE.'),
  'resposta=parte': d('Todas as caixas', 'A mudança vale para todas as caixas desta parte.'),
  'resposta=face': d('Só nesta caixa', 'A mudança vale só para a caixa clicada.'),
  'titulo-prancheta': d('Prancheta', 'Arraste para mudar de lugar (gruda nas outras); clique para o menu rápido.'),
  'prancheta-girar': d('Girar prancheta', 'Troca entre retrato e paisagem.'),
  'prancheta-tamanho': d('Redimensionar', 'Troca o tamanho da folha: A4, A5, A6 ou personalizado.'),
  'prancheta-duplicar': d('Duplicar prancheta', 'Faz uma cópia com os moldes, já ligada às partes.'),
  'prancheta-excluir': d('Excluir prancheta', 'Apaga a prancheta e os moldes dela.', 'Ctrl+Z desfaz'),
  // ── base: moldes e faces ──
  'importar-moldes-btn': d('Importar moldes', 'Traz moldes em PDF, SVG, DXF, PNG ou JPG — vários de uma vez.'),
  detectar: d('Detectar de novo', 'Refaz as faces deste molde a partir das linhas.'),
  'excluir-molde': d('Excluir molde', 'Tira o molde da prancheta.', 'Delete'),
  'ferramenta-molde=selecionar': d('Selecionar', 'Clique numa face para escolher.', 'Esc'),
  'ferramenta-molde=laco': d('Laço', 'Clique nos cantos de uma face nova; feche no 1º ponto ou com Enter.', 'Enter fecha'),
  'ferramenta-molde=dividir': d('Dividir face', 'Dois cliques: a linha corta a face em duas.'),
  'ferramenta-molde=unir': d('Unir faces', 'Selecione uma face e clique na vizinha para virar uma só.'),
  'ferramenta-molde=medir': d('Medir', 'Dois cliques mostram a distância em mm.'),
  'fechar-pontilhado': d('Fechar pontilhado', 'Junta as linhas tracejadas do molde para o sistema encontrar as faces.'),
  'ferramenta=laco': d('Laço', 'Seleciona desenhando à mão livre.'),
  ima: d('Ímã', 'Os cliques grudam no centro da linha do molde.'),
  'alternar-furo': d('Furo', 'Marca ou desmarca esta face como furo (não recebe arte).'),
  'excluir-face': d('Excluir face', 'Apaga a face escolhida.', 'Delete'),
  equivalente: d('Face equivalente', 'Seleciona a face parecida em outro molde.'),
  'medida-ok': d('Usar esta medida', 'Confirma o tamanho real do molde importado.'),
  'medir-2-cliques': d('Medir com 2 cliques', 'Clique nas pontas de uma medida conhecida para acertar a escala.'),
  'confirmar-largura': d('Confirmar', 'Usa a largura informada para o molde.'),
  'unidade-dxf': d('Unidade do DXF', 'Em que unidade o arquivo foi desenhado (mm, cm, polegada).'),
  importar: d('Importar', 'Coloca os moldes na prancheta.'),
  // ── base: passos ──
  passo: d('Passo da base', 'Vai direto para este passo da montagem.'),
  proximo: d('Próximo', 'Segue para o próximo passo.'),
  'aceitar-sugestoes': d('Aceitar sugestões', 'Marca nesta parte todas as faces parecidas que o sistema achou.'),
  'parte-enq': d('Parte', 'Escolhe a parte para ajustar o enquadramento.'),
  instancia: d('Face da parte', 'Escolhe a face para ajustar o enquadramento dela.'),
  modo: d('Enquadramento', 'Como a arte da parte cabe nesta face (preencher, esticar…).'),
  'girar-180': d('Girar 180°', 'Vira a arte desta face de cabeça para baixo.'),
  espelhar: d('Espelhar', 'Espelha a arte desta face.'),
  'posicionar-var=NOME': d('Posicionar NOME', 'Clique na face onde o nome da criança fica.'),
  'posicionar-var=IDADE': d('Posicionar IDADE', 'Clique na face onde a idade fica.'),
  'posicionar-var=HASHTAG': d('Posicionar HASHTAG', 'Clique na face onde a hashtag fica.'),
  'posicionar-var=ARROBA': d('Posicionar @', 'Clique na face onde o @ do ateliê fica.'),
  'composto-linhas': d('Nome composto', 'Nome com dois nomes: numa linha ou em duas.'),
  'escolher-logo': d('Logo', 'Escolhe a logo do ateliê (fica na Identidade).'),
  'gerar-qr': d('Gerar QR', 'Cria o QR Code do link (WhatsApp ou Instagram).'),
  'posicionar-logo': d('Posicionar logo', 'Clique no molde onde a logo fica.'),
  'posicionar-qr': d('Posicionar QR', 'Clique no molde onde o QR fica.'),
  'papel-aba': d('Papel das abas', 'Usa este papel nas abas e faces sem parte.'),
  'papel-abas-pc': d('Papel do computador', 'Escolhe um papel do computador para as abas.'),
  'salvar-base': d('Salvar base', 'Grava a base na Biblioteca (pasta Bases/).', 'Ctrl+S'),
  'abrir-base': d('Abrir base', 'Abre uma base salva na Biblioteca.'),
  // ── tema ──
  'novo-tema': d('Novo tema', 'Cria um tema vazio sobre esta base.'),
  'abrir-tema': d('Abrir tema', 'Abre um tema salvo na Biblioteca.'),
  'salvar-tema': d('Salvar tema', 'Grava o tema na Biblioteca (pasta Temas/).'),
  'pasta=Papéis': d('Papéis', 'Os papéis de fundo da Biblioteca.'),
  'pasta=Elementos': d('Elementos', 'Os elementos (com fundo transparente) da Biblioteca.'),
  'pasta=Cor': d('Cor', 'Preenche a parte com uma cor lisa.'),
  'adicionar-arquivo': d('Adicionar', 'Copia imagens do computador para a Biblioteca.'),
  arquivo: d('Arquivo da Biblioteca', 'Arraste para uma parte ou para uma face; Shift = por cima.'),
  'nova-forma': d('Forma', 'Acrescenta esta forma na parte.'),
  'abrir-caneta': d('Caneta', 'Desenha uma forma livre ponto a ponto.'),
  'escopo-btn=parte': d('Todas as caixas', 'A edição vale para todas as caixas desta parte.'),
  'escopo-btn=face': d('Só nesta caixa', 'A edição vale só para a caixa clicada.'),
  visivel: d('Mostrar / ocultar', 'Esconde a camada sem apagar.'),
  'excluir-camada-tema': d('Excluir camada', 'Apaga a camada do tema.'),
  desvincular: d('Desvincular', 'A camada vira exclusiva desta caixa.'),
  voltar: d('Voltar ao padrão', 'Tira o ajuste desta caixa (volta a seguir as outras).'),
  'voltar-tudo': d('Voltar tudo ao padrão', 'Tira todos os ajustes desta caixa.'),
  'abrir-transicao': d('Transição', 'O 2º papel aparece por cima e some suavemente, revelando o de baixo.'),
  direcao: d('Direção da transição', 'De onde o papel novo aparece e para onde ele some.'),
  'papel-transicao': d('2º papel', 'Usa este papel na transição.'),
  'criar-moldura': d('Moldurinha', 'Bordinha interna na face, contínua ou pesponto. Clique de novo para moldura dupla.'),
  'preset-moldura': d('Molduras salvas', 'Aplica uma moldura guardada.'),
  'moldura-linha=continua': d('Linha contínua', 'Moldura com linha inteira.'),
  'moldura-linha=pesponto': d('Pesponto', 'Moldura tracejada, como costura.'),
  'moldura-cantos=vivos': d('Cantos vivos', 'Cantos retos.'),
  'moldura-cantos=redondos': d('Cantos arredondados', 'Cantos curvos; ajuste o arredondamento.'),
  'salvar-preset-moldura': d('Salvar moldura', 'Guarda esta moldura para reaplicar em outros temas.'),
  'cor-seletor': d('Cor', 'Escolha o tom e a saturação.'),
  'conta-gotas': d('Conta-gotas', 'Clique em qualquer cor da arte para pegar a cor.'),
  'cor-paleta': d('Cor do tema', 'Clique para escolher; duplo clique preenche direto.'),
  'aplicar-cor': d('Preencher com a cor', 'Troca o papel de fundo da parte pela cor.'),
  'aplicar-cor-cima': d('Cor por cima', 'A cor entra por cima dos papéis (para transição ou máscara).'),
  variavel: d('Texto', 'Escolhe qual texto estilizar (nome, idade, hashtag, @).'),
  fonte: d('Fonte', 'A fonte do texto (do computador ou do Google Fonts).'),
  'liberar-fontes': d('Liberar fontes', 'Deixa o MAE usar as fontes instaladas no computador.'),
  'caixa-texto=normal': d('Aa', 'Escreve como foi digitado.'),
  'caixa-texto=alta': d('AA', 'Tudo em maiúsculas.'),
  'caixa-texto=baixa': d('aa', 'Tudo em minúsculas.'),
  ot: d('Recurso da fonte', 'Liga um conjunto de letras alternativas da fonte.'),
  letra: d('Letra', 'Escolha uma variação só para esta letra.'),
  glifo: d('Glifo', 'Usa esta variação na letra escolhida.'),
  'texto-padrao': d('Voltar ao padrão', 'Tira o ajuste deste texto nesta caixa.'),
  'gerar-png-tema': d('PNG de teste', 'Gera uma imagem da folha para conferir o texto.'),
  // ── efeitos e edição da camada ──
  'copiar-estilo': d('Copiar estilo', 'Copia os efeitos desta camada.'),
  'colar-estilo': d('Colar estilo', 'Cola os efeitos copiados nesta camada.'),
  'add-efeito': d('Efeito', 'Acrescenta traçado, sombra, brilho, chanfro ou sobreposição.'),
  'tipo-efeito': d('Tipo de efeito', 'Acrescenta este efeito.'),
  'salvar-preset': d('Salvar preset', 'Guarda só os efeitos (não a fonte) para usar de novo.'),
  'preset-meu': d('Meu preset', 'Aplica este conjunto de efeitos.'),
  'preset-naty': d('Preset da Naty', 'Aplica este conjunto de efeitos da Naty.'),
  'abrir-deformar': d('Deformar', 'Distorcer, perspectiva ou malha.'),
  'mascara-degrade': d('Degradê na máscara', 'A camada some aos poucos.'),
  'pintar-mascara': d('Pintar a máscara', 'Pincel, borracha e seleções para esconder partes da camada.'),
  'tipo-degrade-mascara': d('Tipo de degradê', 'Linear, radial, angular ou refletido.'),
  'editar-mascara': d('Editar máscara', 'Abre a máscara para pintar e selecionar.'),
  'excluir-mascara': d('Excluir máscara', 'Tira a máscara (a camada volta inteira).'),
  'adicionar-ajuste': d('Ajuste', 'Brilho, matiz, níveis, curvas… sem estragar a imagem.'),
  'pintar-camada': d('Pintar', 'Pinta numa camada nova por cima.'),
  'mascara-no': d('Máscara', 'Degradê para a camada sumir aos poucos.'),
  'adicionar-ajuste-no': d('Ajuste', 'Brilho, matiz, níveis, curvas… sem estragar a imagem.'),
  // ── editor de máscara / pixels ──
  'modo-pixels=mascara': d('Máscara', 'Pinte para esconder (borracha) ou revelar (pincel) partes da camada.'),
  'modo-pixels=pintura': d('Pintura', 'Pinta numa camada nova por cima.'),
  'modo-pixels=deformar': d('Deformar', 'Arraste as alças para distorcer a imagem.'),
  'salvar-pixels': d('Aplicar', 'Guarda o que foi feito (um passo só no Ctrl+Z do tema).'),
  'ferramenta=retangulo': d('Letreiro retangular', 'Seleciona um retângulo.'),
  'ferramenta=elipse': d('Letreiro elíptico', 'Seleciona uma elipse.'),
  'ferramenta=poligonal': d('Laço poligonal', 'Seleciona clicando ponto a ponto; duplo clique fecha.'),
  'ferramenta=varinha': d('Varinha mágica', 'Seleciona a área de cor parecida.'),
  'ferramenta=intervalo': d('Intervalo de cores', 'Seleciona todos os pixels com a cor clicada.'),
  'ferramenta=objeto': d('Objeto automático', 'A IA separa o objeto clicado (Shift+clique tira uma parte).'),
  'ferramenta=pincel': d('Pincel', 'Na máscara: revela. Na pintura: pinta.'),
  'ferramenta=borracha': d('Borracha', 'Na máscara: esconde. Na pintura: apaga.'),
  'ferramenta=lata': d('Lata de tinta', 'Preenche a área clicada (Alt: esconde na máscara).'),
  'ferramenta=degrade': d('Degradê', 'Arraste para criar o degradê.'),
  'ferramenta=contagotas': d('Conta-gotas', 'Pega a cor clicada.'),
  'op-selecao': d('Combinar seleção', 'A nova seleção substitui, soma, subtrai ou intersecta a atual.'),
  'tipo-degrade': d('Tipo de degradê', 'Linear, radial, angular ou refletido.'),
  paleta: d('Paleta do tema', 'Usa esta cor dos papéis do tema.'),
  'warp=distorcer': d('Distorcer', 'Mexa os 4 cantos livremente.'),
  'warp=perspectiva': d('Perspectiva', 'Mexa um canto e o par acompanha (trapézio).'),
  'warp=malha': d('Malha 3×3', 'Curva a imagem com 9 alças.'),
  'selecionar-tudo': d('Selecionar tudo', 'Seleciona a imagem inteira.', 'Ctrl+A'),
  desmarcar: d('Desmarcar', 'Tira a seleção.', 'Ctrl+D'),
  'inverter-selecao': d('Inverter seleção', 'Seleciona o que estava de fora.', 'Ctrl+Shift+I'),
  'selecao-mascara': d('Virar máscara', 'A seleção vira a máscara da camada.'),
  'tirar-degrade': d('Tirar o degradê', 'Remove o degradê da máscara.'),
  // ── editor de imagem ──
  'salvar-design': d('Salvar design', 'Grava o design na Biblioteca (pasta Designs/).'),
  'tamanho-novo': d('Tamanho do design', 'Tamanhos de impressão e de marketplace (Shopee, Instagram…).'),
  'novo-design': d('Novo design', 'Começa um design no tamanho escolhido.'),
  'abrir-design': d('Abrir design', 'Abre um design salvo (do computador ou da nuvem).'),
  pagina: d('Página', 'Vai para esta página do design.'),
  'nova-pagina': d('Nova página', 'Acrescenta uma página em branco.'),
  'duplicar-pagina': d('Duplicar página', 'Copia a página com as camadas.'),
  'add-texto': d('Texto', 'Acrescenta uma caixa de texto.'),
  'add-forma': d('Forma', 'Retângulo, círculo, estrela, coração, seta…'),
  'add-ajuste': d('Camada de ajuste', 'Ajusta tudo o que está abaixo dela.'),
  'importar-arquivo': d('Importar', 'PSD (com as camadas), PDF (por objetos) ou imagem.'),
  'alinhar=l': d('Alinhar à esquerda', 'Encosta na borda esquerda da página.'),
  'alinhar=c': d('Centralizar na horizontal', 'Coloca no meio da página, na horizontal.'),
  'alinhar=m': d('Centralizar na vertical', 'Coloca no meio da página, na vertical.'),
  preencher: d('Preencher a página', 'A imagem cobre a página toda.'),
  'espelhar-imagem': d('Espelhar', 'Vira a imagem como num espelho.'),
  'fonte-texto': d('Fonte', 'A fonte do texto.'),
  filtro: d('Filtro', 'Um visual pronto (Vivo, Suave, P&B…).'),
  'pixels-imagem': d('Editar pixels', 'Máscara, seleção, pintura ou deformar.'),
  'formato-imagem': d('Formato', 'PNG, JPG, WebP ou PDF com as páginas juntas.'),
  'tamanho-exportar': d('Tamanho', 'Original (300 dpi) ou no tamanho de um marketplace.'),
  'exportar-design': d('Exportar', 'Grava as páginas na Biblioteca (e em Meus arquivos, se marcado).'),
  'add-imagem': d('Imagem', 'Traz uma imagem do computador (vai para Elementos/).'),
  'add-solida': d('Cor sólida', 'Acrescenta uma camada de cor lisa.'),
  olho: d('Mostrar / ocultar', 'Esconde a camada sem apagar.'),
  cadeado: d('Travar', 'Impede de mexer na camada sem querer.'),
  subir: d('Subir camada', 'Passa a camada para cima.', 'Ctrl+]'),
  descer: d('Descer camada', 'Passa a camada para baixo.', 'Ctrl+['),
  agrupar: d('Agrupar', 'Junta as camadas num grupo.', 'Ctrl+G'),
  desagrupar: d('Desagrupar', 'Desfaz o grupo.', 'Shift+Ctrl+G'),
  duplicar: d('Duplicar camada', 'Copia a camada.', 'Ctrl+J'),
  excluir: d('Excluir camada', 'Apaga a camada.', 'Delete'),
  mesclagem: d('Modo de mesclagem', 'Como a camada se mistura com a de baixo (multiplicação, tela…).'),
  // ── exportar ──
  'aprovacao-agrupar': d('Aprovação', 'Uma imagem só ou uma por molde.'),
  'gerar-aprovacao': d('Gerar JPG', 'Arte para a cliente aprovar (com marca d’água).'),
  formato: d('Formato', 'PDF ou PNG em 300 dpi.'),
  'agrupar-arquivos': d('Agrupar arquivos', 'Um arquivo por prancheta ou por molde.'),
  linhas: d('Linhas de corte', 'Imprime ou esconde as linhas do molde.'),
  'marca-prancheta': d('Marca de registro', 'A marca da sua máquina de corte nesta folha.'),
  'adicionar-marca': d('Adicionar marca', 'Cadastra a marca de registro da máquina (PDF).'),
  'gerar-impressao': d('Arte pra impressão', 'Gera o arquivo com sobra, linhas e marca de registro.'),
  'fechar-lembrete': d('Entendi', 'Fecha o lembrete.'),
  'marca-apliques': d('Marca dos apliques', 'A marca de registro das folhas de apliques.'),
  'gerar-apliques': d('Apliques 3D', 'Organiza os apliques na folha e gera os 2 PNG (impressão e silhueta).'),
  // ── pedidos, loja, tutorial ──
  'escolher-tema-pedido': d('Tema do pedido', 'Escolhe o tema quando o pedido não diz qual é.'),
  'escala-nome-pedido': d('Tamanho do nome', 'Muda o tamanho do nome só neste pedido (o tema não muda).'),
  'ver-miniatura': d('Ver', 'Mostra a prévia deste pedido.'),
  'filtro-massa': d('Filtro', 'Mostra os pedidos pendentes, já gerados ou todos.'),
  'tema-linha': d('Tema', 'O tema deste pedido.'),
  'lembrar-vinculo': d('Sempre usar', 'Este produto passa a usar este tema nos próximos pedidos.'),
  'escala-linha': d('Tamanho do nome', 'Muda o tamanho do nome só neste pedido.'),
  'formato-massa': d('Formato', '1 PDF por pedido ou 1 PDF por folha.'),
  parar: d('Parar', 'Para depois do pedido que está sendo gerado.'),
  'gerar-todos': d('Gerar artes', 'Gera a arte de todos os pedidos marcados.'),
  'abrir-loja': d('Loja da Naty', 'Packs de temas prontos para comprar e aplicar.'),
  'baixar-pack': d('Baixar e aplicar', 'Aplica o pack nesta base.'),
  'comprar-pack': d('Comprar', 'Compra o pack (Pix ou cartão).'),
  publicar: d('Publicar na Loja', 'Coloca este tema à venda na Loja (só a Naty).'),
  'fechar-tutorial': d('Fechar', 'Fecha o tutorial.'),
  'proximo-tutorial': d('Próximo', 'Próxima dica do tutorial.'),
  'concluir-tutorial': d('Começar', 'Fecha o tutorial e começa.'),
  'salvar-calibracao': d('Salvar calibração', 'Guarda a medida da tela para o tamanho real.'),
  'gerar-png': d('PNG de teste', 'Gera uma imagem da folha pelo motor.'),
  'abrir-teste': d('Abrir teste', 'Abre o arquivo de teste gravado na Biblioteca.'),
  'caneta-aberta': d('Linha aberta', 'Termina a forma sem fechar.'),
  'caneta-fechar': d('Fechar forma', 'Termina a forma ligando no 1º ponto.'),
}

/** Por texto do botão (sem acento/maiúsculas), para os botões sem atributo próprio. */
export const DICAS_TEXTO: Record<string, Dica> = {
  ajustar: d('Ajustar à tela', 'Mostra todas as pranchetas na tela.', 'Ctrl+0'),
  'calibrar tela': d('Calibrar tela', 'Mede a tela com um cartão para o tamanho real ficar exato.'),
  cancelar: d('Cancelar', 'Fecha sem guardar.', 'Esc'),
  'voltar ao padrao': d('Voltar ao padrão', 'Desfaz o ajuste e volta ao original.'),
  'trocar pasta': d('Trocar pasta', 'Escolhe outra pasta como Biblioteca MAE.'),
  reconectar: d('Reconectar', 'Libera de novo a pasta Biblioteca MAE (o navegador pede 1 clique por sessão).'),
  'escolher pasta': d('Escolher pasta', 'Escolha a pasta Biblioteca MAE no computador.'),
  'abrir o editor de temas': d('Editor de temas', 'Abre o editor para criar ou corrigir um tema.'),
  'desfazer ponto': d('Desfazer ponto', 'Tira o último ponto da caneta.'),
  'outra base…': d('Outra base', 'Troca a base deste tema.'),
  'tirar deformacao': d('Tirar deformação', 'Volta a imagem ao formato original.'),
  expandir: d('Expandir', 'Aumenta a seleção alguns pixels.'),
  contrair: d('Contrair', 'Diminui a seleção alguns pixels.'),
  suavizar: d('Suavizar', 'Arredonda a borda da seleção.'),
  'limpar pintura da mascara': d('Limpar máscara', 'Apaga o que foi pintado na máscara.'),
  voltar: d('Voltar', 'Volta para o passo anterior.'),
  '← voltar': d('Voltar', 'Volta para o passo anterior.'),
  continuar: d('Continuar', 'Segue para o próximo passo.'),
  comprar: d('Comprar', 'Finaliza a compra.'),
  tirar: d('Tirar', 'Remove este item.'),
  'listar fontes instaladas': d('Fontes do computador', 'Mostra as fontes instaladas para usar nos textos.'),
  'gravar teste': d('Gravar teste', 'Grava um arquivo de teste na Biblioteca.'),
  'ler teste': d('Ler teste', 'Lê o arquivo de teste da Biblioteca.'),
  'igual em todas': d('Igual em todas', 'Copia este enquadramento para as outras faces da parte.'),
  'distorcer / perspectiva / malha…': d('Deformar', 'Distorcer, perspectiva ou malha.'),
  '+': d('Aumentar', 'Aumenta um pouco.'),
  '−': d('Diminuir', 'Diminui um pouco.'),
  '?': d('Como usar', 'Abre o passo a passo do Método MAE.'),
}

export const normalizarTexto = (s: string) => s.normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/\s+/g, ' ').trim().toLowerCase()

/** "Nome — frase (Ctrl+Z)" → dica; usado quando o botão só tem o title. */
export function dicaDoTitulo(t: string): Dica | null {
  const titulo = (t || '').trim()
  if (!titulo) return null
  const at = titulo.match(/\(((?:Ctrl|Shift|Alt|Delete|Esc|Enter)[^)]*)\)\s*$/i)
  const semAtalho = at ? titulo.slice(0, at.index).trim() : titulo
  const [nome, ...resto] = semAtalho.split(/\s+[—–-]\s+/)
  return { nome: nome.trim(), frase: resto.join(' — ').trim(), ...(at ? { atalho: at[1] } : {}) }
}

/** A dica de um botão: pelos atributos data-*, pelo texto, ou pelo title/aria-label. */
export function dicaDe(attrs: Record<string, string>, texto: string, titulo: string, aria: string): Dica | null {
  for (const [k, v] of Object.entries(attrs)) {
    const nome = k.replace(/^data-/, '')
    if (v && DICAS[`${nome}=${v}`]) return DICAS[`${nome}=${v}`]
  }
  for (const k of Object.keys(attrs)) { const nome = k.replace(/^data-/, ''); if (DICAS[nome]) return DICAS[nome] }
  const t = normalizarTexto(texto)
  if (t && DICAS_TEXTO[t]) return DICAS_TEXTO[t]
  const doTitulo = dicaDoTitulo(titulo) ?? dicaDoTitulo(aria)
  if (doTitulo) return { ...doTitulo, nome: doTitulo.nome || texto.trim(), frase: doTitulo.frase }
  return texto.trim() ? { nome: texto.trim(), frase: '' } : null
}
