import type { EntradaConhecimento } from '../tipos'

// Base de conhecimento do módulo COMPRAS (Supply) — padrão-ouro (8 seções).
export const ENTRADAS: EntradaConhecimento[] = [
  // 1) VISÃO GERAL DO MÓDULO
  {
    slug: 'compras-visao-geral',
    modulo: 'Compras',
    tela: 'Compras — Visão geral',
    caminho: 'Compras → Visão geral',
    palavrasChave: 'compras, módulo de compras, visão geral de compras, quanto gastei com material, quanto comprei, volume de compras, de quem eu mais compro, fornecedor que mais compro, material que mais compro, o que mais compro, evolução de preço, ativar compras, ligar compras, supply, insumos',
    conteudo: '📍 ONDE FICA: Menu → Compras → Visão geral. O grupo "Compras" só aparece no menu depois que você ativa o módulo (em Módulos, ligue "Compras"). Dentro dele ficam: Visão geral, Fornecedores, Pesquisar preço, Pedido de compra, Histórico de compras e Ofertas & Cupons.\n\n💡 O QUE É E PRA QUE SERVE: É o painelzinho que responde, num relance, "quanto eu comprei e de quem?". Ela junta tudo que você registrou nos Pedidos de compra e mostra: o volume gasto no período, quantas compras você fez, de qual fornecedor você mais compra, qual material pesa mais no seu bolso e como o preço dos seus materiais evoluiu. Serve para você enxergar para onde vai o dinheiro dos insumos e negociar melhor.\n\n✅ ANTES DE COMEÇAR: Você precisa ter o módulo Compras ativado e ter feito pelo menos um Pedido de compra — é dele que a Visão geral tira os números. Se estiver tudo zerado, é só porque você ainda não registrou compras. É uma tela só de administradora.\n\n👣 PASSO A PASSO:\n1. Abra Compras → Visão geral.\n2. No canto de cima, escolha o período (Últimos 30 dias, 90 dias, 12 meses ou Tudo).\n3. Leia os cartões: "Volume comprado" (total gasto), "Nº de compras" (e quantos itens), "Fornecedor top" (de quem você mais compra) e "Material mais comprado" (o que mais pesa).\n4. Desça para os rankings "De quem você mais compra" e "O que mais pesa nas compras" (com barrinhas de proporção).\n5. No fim, "Evolução de preço por material" mostra se o preço de cada material subiu ou baixou (com a seta e o %).\n\n🧮 COMO FUNCIONA POR TRÁS: Ela lê os itens dos seus Pedidos de compra concluídos no período. "Fornecedor top" e "material que mais pesa" são pelo valor gasto (R$), não pela quantidade. A evolução de preço compara o primeiro com o último preço pago por unidade daquele material. Tudo é só leitura — não mexe em estoque nem financeiro.\n\n⚠️ ERROS COMUNS: 1) "Não aparece nada" — você ainda não fez Pedidos de compra, ou o período está curto demais (troque para "Tudo"). 2) Confundir "mais comprado" (o que mais gasta) com "maior quantidade" — aqui é por valor. 3) Achar que a Visão geral registra compras: quem registra é o Pedido de compra; aqui só se lê.\n\n💬 EXEMPLO SOFIA: "Quer saber para onde vai o dinheiro do material, amiga? Abre Compras → Visão geral e escolhe o período. Ali em cima você vê quanto gastou, de quem mais compra e qual material pesa mais. E lá embaixo tem a evolução de preço — se a fita subiu, você descobre na hora e já pode pesquisar um fornecedor melhor 🧡"',
    faq: [
      { pergunta: 'Como eu ativo o módulo de Compras?', resposta: 'Vá em Módulos (o hub) e ligue "Compras". Assim que ativar, o grupo "Compras" aparece no seu menu com todos os submenus: Visão geral, Fornecedores, Pesquisar preço, Pedido de compra, Histórico e Ofertas & Cupons. A ativação é reversível e não apaga nada.' },
      { pergunta: 'De qual fornecedor eu mais compro?', resposta: 'Abra Compras → Visão geral e olhe o cartão "Fornecedor top" e o ranking "De quem você mais compra". Ele soma o valor das suas compras por fornecedor no período que você escolher (30/90/365 dias ou tudo). É pelo valor gasto em reais.' },
      { pergunta: 'Qual material eu mais compro?', resposta: 'Na Visão geral de Compras, o cartão "Material mais comprado" e o ranking "O que mais pesa nas compras" mostram isso — pelo valor gasto. Assim você sabe qual insumo mais impacta seu custo e vale negociar ou pesquisar preço.' },
    ],
  },

  // 2) PEDIDO DE COMPRA (3-EM-1)
  {
    slug: 'compras-pedido',
    modulo: 'Compras',
    tela: 'Pedido de compra',
    caminho: 'Compras → Pedido de compra',
    palavrasChave: 'pedido de compra, registrar compra, comprei material, cadastrar compra, dar entrada no estoque, atualizar custo do material, comprei mais barato, comprei fiado, comprei a prazo, contas a pagar da compra, nota da compra, fornecedor da compra, quantas folhas, preço do pacote, registra uma compra',
    conteudo: '📍 ONDE FICA: Menu → Compras → Pedido de compra.\n\n💡 O QUE É E PRA QUE SERVE: É onde você registra uma compra de material — e ela é "3 em 1": num único registro, o sistema (1) gera as contas a pagar no Financeiro, (2) atualiza o custo do material na Precificação e (3) dá entrada no estoque. Ou seja, você anota a compra uma vez e ela se espalha sozinha para o financeiro, o custo e o estoque, sem retrabalho.\n\n✅ ANTES DE COMEÇAR: Tenha o material já cadastrado (Precificação → Materiais) e, de preferência, o fornecedor (Compras → Fornecedores). Saiba o que comprou: quantos pacotes, quantas unidades por pacote e o preço do pacote. É tela de administradora.\n\n👣 PASSO A PASSO:\n1. Abra Compras → Pedido de compra.\n2. Escolha o fornecedor (ou cadastre um novo).\n3. Informe a data e, se tiver, o número da nota.\n4. Adicione os itens: o material, quantos pacotes, quantas unidades por pacote e o preço do pacote. O sistema calcula o preço por unidade.\n5. Se o preço mudou desde a última vez, marque "atualizar custo" naquele item — isso atualiza o custo na Precificação e reflete nos produtos que usam o material.\n6. Escolha se quer dar entrada no estoque (para materiais que você controla) e se quer gerar contas a pagar (à vista ou a prazo/fiado, com vencimento e parcelas).\n7. Conclua. Pronto: contas a pagar criadas, custo atualizado e estoque com entrada.\n\n🧮 COMO FUNCIONA POR TRÁS: As contas a pagar entram no Financeiro vinculadas à compra (dá para conferir no Histórico, com status pendente/quitado). A entrada de estoque é idempotente (não duplica se você repetir). Ao atualizar o custo, o sistema recalcula o custo do material e propaga para as variações dos produtos que o utilizam (resync), então seus preços passam a refletir o novo custo.\n\n⚠️ ERROS COMUNS: 1) Esquecer de marcar "atualizar custo" quando o preço mudou — aí a Precificação continua com o custo antigo. 2) Confundir preço do pacote com preço por unidade (informe o do pacote; o sistema divide). 3) Gerar contas a pagar sem querer para uma compra à vista já paga — nesse caso marque como pago/à vista.\n\n💬 EXEMPLO SOFIA: "Comprou material, amiga? Registra em Compras → Pedido de compra que ele faz o serviço triplo pra você: já lança as contas a pagar, atualiza o custo lá na precificação e dá entrada no estoque. Se você pagou mais barato dessa vez, marca "atualizar custo" que seus preços se ajustam sozinhos 🧡"',
    faq: [
      { pergunta: 'Comprei o material mais barato — como atualizo o custo?', resposta: 'Ao registrar em Compras → Pedido de compra, marque a opção "atualizar custo" naquele item. O sistema atualiza o custo do material na Precificação e propaga para os produtos que usam esse material (resync), então o preço deles passa a refletir o novo custo. Você não precisa mexer produto por produto.' },
      { pergunta: 'A compra gera contas a pagar sozinha? E atualiza o estoque?', resposta: 'Sim, as duas coisas — é o "3 em 1". Ao concluir o Pedido de compra, ele gera as contas a pagar no Financeiro (à vista ou a prazo/fiado, com vencimento e parcelas), dá entrada no estoque do material e, se você marcar, atualiza o custo na Precificação. Tudo de uma vez.' },
      { pergunta: 'Comprei fiado / a prazo, como registro?', resposta: 'No Pedido de compra, ao gerar as contas a pagar, escolha o vencimento e o número de parcelas. Assim a compra fica como conta a pagar em aberto no Financeiro, com o vencimento certo — e some do "a pagar" quando você marcar como quitada.' },
    ],
  },

  // 3) HISTÓRICO DE COMPRAS
  {
    slug: 'compras-historico',
    modulo: 'Compras',
    tela: 'Histórico de compras',
    caminho: 'Compras → Histórico de compras',
    palavrasChave: 'histórico de compras, minhas compras anteriores, o que já comprei, evolução de preço, o preço subiu, offset subiu, comparar com o mercado, boa compra, paguei caro, contas a pagar da compra, filtrar compras por fornecedor material período',
    conteudo: '📍 ONDE FICA: Menu → Compras → Histórico de compras.\n\n💡 O QUE É E PRA QUE SERVE: É a lista de tudo que você já comprou, com filtros. Mostra cada item comprado (fornecedor, material, quantidade, preço por unidade, valor), o vínculo com as contas a pagar (pendente/quitado), a evolução de preço por material e um selo comparando o que você pagou com o preço de mercado ("boa compra ✅ / na média / acima da média ⚠️").\n\n✅ ANTES DE COMEÇAR: Precisa ter Pedidos de compra registrados. Tela de administradora.\n\n👣 PASSO A PASSO:\n1. Abra Compras → Histórico de compras.\n2. Use os filtros (fornecedor, material, período de/até) para achar o que quer.\n3. Em cada item, veja o preço por unidade, o selo de comparação com o mercado e a etiqueta de contas a pagar (quanto ainda está pendente).\n4. Na seção "Evolução de preço por material", veja se o preço subiu ou baixou (primeiro → último, com o %).\n\n🧮 COMO FUNCIONA POR TRÁS: O selo de mercado compara o preço por unidade que você pagou com o índice de preços da comunidade (o mesmo do "Pesquisar preço"): até ~2% abaixo = boa compra; ~5% acima = acima da média. As contas a pagar vêm do Financeiro, vinculadas à compra. Tudo é só leitura.\n\n⚠️ ERROS COMUNS: 1) Não achar uma compra por causa do filtro de período — amplie as datas. 2) Achar que o selo "acima da média" é erro: é só um aviso carinhoso de que talvez dê pra pesquisar um fornecedor melhor.\n\n💬 EXEMPLO SOFIA: "Quer saber se o offset subiu, amiga? Abre Compras → Histórico. Ali tem a evolução de preço de cada material e um selinho dizendo se você fez uma boa compra ou pagou acima da média. Assim você negocia com dados na mão 🧡"',
    faq: [
      { pergunta: 'Onde vejo minhas compras anteriores?', resposta: 'Em Compras → Histórico de compras. Você pode filtrar por fornecedor, material e período. Cada item mostra quanto você pagou por unidade, o vínculo com as contas a pagar e uma comparação com o preço de mercado.' },
      { pergunta: 'O preço do meu material subiu — como sei?', resposta: 'Abra Compras → Histórico de compras e olhe a seção "Evolução de preço por material": ela mostra o primeiro e o último preço por unidade que você pagou, com a seta e o percentual de variação. A Visão geral de Compras também traz essa evolução.' },
      { pergunta: 'Estou pagando caro no meu material?', resposta: 'No Histórico de compras, cada item traz um selo comparando o que você pagou com o preço de mercado ("boa compra", "na média" ou "acima da média"). Se aparecer "acima da média", vale usar Compras → Pesquisar preço para achar um fornecedor melhor.' },
    ],
  },

  // 4) OFERTAS & CUPONS (VITRINE)
  {
    slug: 'compras-ofertas',
    modulo: 'Compras',
    tela: 'Ofertas & Cupons',
    caminho: 'Compras → Ofertas & Cupons',
    palavrasChave: 'ofertas, cupons, desconto de parceiro, ofertas de parceiros, cupom de desconto, vantagem na compra, promoção de material, aproveitar oferta, copiar cupom, ofertas e cupons',
    conteudo: '📍 ONDE FICA: Menu → Compras → Ofertas & Cupons.\n\n💡 O QUE É E PRA QUE SERVE: É uma vitrine de ofertas e cupons de parceiros de insumos (lojas de material). Cada oferta vira um cartão com o logo do parceiro, o desconto em destaque, um título, uma descrição e o botão para aproveitar. É uma vantagem na hora de comprar material mais barato.\n\n✅ ANTES DE COMEÇAR: Nada além de ter o módulo Compras. As ofertas são publicadas pela equipe do SOA (parceiros) — você só aproveita.\n\n👣 PASSO A PASSO:\n1. Abra Compras → Ofertas & Cupons.\n2. Veja os cartões (3 por linha no computador). Cada um tem o logo, o desconto, o título e a descrição.\n3. Se tiver cupom, clique em "copiar código" para usar na loja do parceiro.\n4. Clique em "Aproveitar oferta" — abre o site do parceiro numa nova aba.\n\n🧮 COMO FUNCIONA POR TRÁS: Só aparecem ofertas ativas e dentro da validade, na ordem definida pela equipe. Os links abrem em nova aba. É só leitura — nada é cobrado por aqui; você compra no site do parceiro.\n\n⚠️ ERROS COMUNS: 1) "Sumiu uma oferta" — ela pode ter expirado ou sido desativada; é normal. 2) Achar que o SOA vende o material: não — a compra é feita no site do parceiro, pelo link.\n\n💬 EXEMPLO SOFIA: "Passa em Compras → Ofertas & Cupons de vez em quando, amiga — tem desconto de parceiros de material lá. Se tiver um cupom, é só copiar e usar na loja. Toda economia no insumo vira margem pra você 🧡"',
    faq: [
      { pergunta: 'Onde vejo as ofertas e cupons dos parceiros?', resposta: 'Em Compras → Ofertas & Cupons. Cada oferta é um cartão com o logo do parceiro, o desconto, o título e um botão "Aproveitar oferta" que abre o site do parceiro. Se houver cupom, dá para copiar o código com um clique.' },
      { pergunta: 'Só aparecem ofertas ativas?', resposta: 'Sim. A vitrine mostra apenas ofertas ativas e dentro da validade, na ordem definida pela equipe. Se uma oferta expirou ou foi desativada, ela deixa de aparecer — isso é normal.' },
    ],
  },
]
